apiVersion: v1
kind: Service
metadata:
  labels:
    app: ps-editor
  name: ps-editor
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ps-editor
